name: code-analysis

on:
    push:
        branches-ignore:
            - main

jobs:
    code-analysis:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"

            - name: Install dependencies
              run: |
                  npm i

            - name: Create env file
              run: node cli/index create env-file -p

            # - name: Generate GraphQL types
            #   run: npx graphql-codegen

            - name: Run prettier
              run: npx prettier --write .

            - name: No changes to commit
              run: |
                  git diff --exit-code

            - name: TypeScript check
              run: npx tsc

            - name: ESLint check
              run: npx eslint . --max-warnings=0

            - name: Tests
              run: npm test
